export const membersConstants = {
    MEMBERS_REQUEST: 'MEMBERS_LOAD_REQUEST',
    MEMBERS_SUCCESS: 'MEMBERS_LOAD_SUCCESS',
    MEMBERS_FAILURE: 'MEMBERS_LOAD_FAILURE',

    ADD_MEMBER_REQUEST: 'MEMBERS_ADD_REQUEST',
    ADD_MEMBER_SUCCESS: 'MEMBERS_ADD_SUCCESS',
    ADD_MEMBER_FAILURE: 'MEMBERS_ADD_FAILURE',

    DELETE_MEMBER_REQUEST: 'MEMBERS_DELETE_REQUEST',
    DELETE_MEMBER_SUCCESS: 'MEMBERS_DELETE_SUCCESS',
    DELETE_MEMBER_FAILURE: 'MEMBERS_DELETE_FAILURE',

    UPDATE_MEMBER_REQUEST: 'MEMBERS_UPDATE_REQUEST',
    UPDATE_MEMBER_SUCCESS: 'MEMBERS_UPDATE_SUCCESS',
    UPDATE_MEMBER_FAILURE: 'MEMBERS_UPDATE_FAILURE',

    EDIT_MEMBER: 'MEMBERS_EDIT',
    STOP_EDIT_MEMBER: 'MEMBERS_STOP_EDIT',

    SUBSCRIPTION_REQUEST: 'SUBSCRIPTION_REQUEST',
    SUBSCRIPTION_SUCCESS: 'SUBSCRIPTION_SUCCESS',
    SUBSCRIPTION_FAILURE: 'SUBSCRIPTION_FAILURE'
}