export const moviesConstants = {
    MOVIES_REQUEST: 'MOVIES_LOAD_REQUEST',
    MOVIES_SUCCESS: 'MOVIES_LOAD_SUCCESS',
    MOVIES_FAILURE: 'MOVIES_LOAD_FAILURE',

    ADD_MOVIE_REQUEST: 'MOVIES_ADD_REQUEST',
    ADD_MOVIE_SUCCESS: 'MOVIES_ADD_SUCCESS',
    ADD_MOVIE_FAILURE: 'MOVIES_ADD_FAILURE',

    DELETE_MOVIE_REQUEST: 'MOVIES_DELETE_REQUEST',
    DELETE_MOVIE_SUCCESS: 'MOVIES_DELETE_SUCCESS',
    DELETE_MOVIE_FAILURE: 'MOVIES_DELETE_FAILURE',

    UPDATE_MOVIE_REQUEST: 'MOVIES_UPDATE_REQUEST',
    UPDATE_MOVIE_SUCCESS: 'MOVIES_UPDATE_SUCCESS',
    UPDATE_MOVIE_FAILURE: 'MOVIES_UPDATE_FAILURE',

    EDIT_MOVIE: 'MOVIES_EDIT',
    STOP_EDIT_MOVIE: 'MOVIES_STOP_EDIT',

    SEARCH_TYPED: 'MOVIES_SEARCH_TYPED'
}