export const userConstants = {
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    SIGNUP_REQUEST: 'USERS_SIGNUP_REQUEST',
    SIGNUP_SUCCESS: 'USERS_SIGNUP_SUCCESS',
    SIGNUP_FAILURE: 'USERS_SIGNUP_FAILURE',

    CHECK_SESSION_TIMEOUT: 'USERS_CHECK_TIMEOUT',
    LOGOUT: 'USERS_LOGOUT',

    USERS_REQUEST: 'USERS_LOAD_REQUEST',
    USERS_SUCCESS: 'USERS_LOAD_SUCCESS',
    USERS_FAILURE: 'USERS_LOAD_FAILURE',

    ADD_USER_REQUEST: 'USERS_ADD_REQUEST',
    ADD_USER_SUCCESS: 'USERS_ADD_SUCCESS',
    ADD_USER_FAILURE: 'USERS_ADD_FAILURE',

    DELETE_USER_REQUEST: 'USERS_DELETE_REQUEST',
    DELETE_USER_SUCCESS: 'USERS_DELETE_SUCCESS',
    DELETE_USER_FAILURE: 'USERS_DELETE_FAILURE',

    UPDATE_USER_REQUEST: 'USERS_UPDATE_REQUEST',
    UPDATE_USER_SUCCESS: 'USERS_UPDATE_SUCCESS',
    UPDATE_USER_FAILURE: 'USERS_UPDATE_FAILURE',
    
    EDIT_USER: 'USERS_EDIT',
    STOP_EDIT_USER: 'USERS_STOP_EDIT'
}